Repository zowe/zlux-app-server, pull requests merged in 2023-07, with the labels that each got.

#255 Extra check between "saf" auth and "fallback" auth
  bin/internal-install.sh
Labels: size/XS

#269 Apply zip pr 3309 to zlux
  schemas/plugindefinition-schema.json
Labels: size/XS

#268 Fixed env merging to wrong part of yaml heirarchy
  bin/install-app.sh
  defaults/serverConfig/defaults.yaml
  lib/zluxArgs.js
Labels: size/S

#270 Bugfix for exception when zowe.environments exists
  lib/zluxArgs.js
Labels: size/XS

#271 Update container-detecting var
  defaults/serverConfig/defaults.yaml
Labels: size/XS

#273 Sync staging with RC
  bin/install-app.sh
  defaults/serverConfig/defaults.yaml
  lib/zluxArgs.js
  schemas/plugindefinition-schema.json
Labels: size/M

#266 Update defaults logic for multi-pem
  CHANGELOG.md
  defaults/serverConfig/defaults.yaml
Labels: size/S
