Repository zowe/zlux-app-server, pull requests merged in 2024-11, with the labels that each got.

#324 Remove node validate script
  CHANGELOG.md
  bin/start.sh
  bin/validate.sh
  manifest.yaml
Labels: size/S

#325 Remove node validate script (v3)
  CHANGELOG.md
  bin/start.sh
  bin/validate.sh
  manifest.yaml
Labels: size/S

#326 Read ssh/telnet port from /etc
  CHANGELOG.md
  defaults/serverConfig/defaults.yaml
  lib/initUtils.js
Labels: size/M

#327 Read ssh/telnet port from /etc: function and regex update
  lib/initUtils.js
Labels: size/XS

#317 Do not log into `zowe.runtimeDirectory`
  CHANGELOG.md
  bin/utils/setup-logs.sh
Labels: size/M
