Repository zowe/zlux-app-server, pull requests merged in 2024-08, with the labels that each got.

#310 Merge Rc with staging
  defaults/serverConfig/defaults.yaml
Labels: size/XS

#312 Update V3 staging
  CHANGELOG.md
  README.md
  bin/configure.sh
  bin/init/plugins-init.js
  bin/init/plugins-init.sh
  bin/start.sh
  bin/validate.sh
  defaults/serverConfig/defaults.yaml
  lib/initInstance.js
  lib/initUtils.js
  lib/zluxArgs.js
  package-lock.json
  package.json
  zss.apiml_static_reg.yaml.template
Labels: size/XL

#307 Updating the readme with better instructions and swift development.
  README.md
Labels: size/M

#308 Feature/v3/entrypoint schema
  schemas/plugindefinition-schema.json
Labels: size/S

#318 Update build workflow
  .github/workflows/build-core.yml
Labels: size/XS
