Repository zowe/zlux-app-server, pull requests merged in 2025-02, with the labels that each got.

#334 Add option to trace eureka registration
  CHANGELOG.md
  schemas/app-server-config.json
Labels: size/S

#281 reject PR if identical to pull_request_template.md
  .github/workflows/build-core.yml
  .github/workflows/set-changelog.js
  CHANGELOG.md
Labels: size/L

#335 Update server-plugins-api.yaml to fix query parameter (v3)
  doc/swagger/server-plugins-api.yaml
Labels: size/XS
